# These are supported funding model platforms

github: [Patel230] # Replace with your GitHub username
custom: ['https://www.buymeacoffee.com/lakshmanpatel', 'https://paypal.me/lakshmanpatel'] # Replace with your own links
