/**
 * Gallery images ship as full-size WebP plus a 640px "-thumb" derivative
 * (generated by scripts/optimize-gallery-images.mjs). Grid cards and the
 * lightbox thumbnail strip use the small file; the carousel uses the full one.
 */
export function thumbSrc(src) {
  return src.replace(/\.webp$/, '-thumb.webp')
}
