/**
 * Gallery images ship as full-size WebP plus a 640px "-thumb" derivative
 * (generated by scripts/optimize-gallery-images.mjs). Grid cards and the
 * lightbox thumbnail strip use the small file; the carousel uses the full one.
 */
export function thumbSrc(src) {
  return src.replace(/\.webp$/, '-thumb.webp')
}

/**
 * Resolve the 900px "medium" derivative (scripts/generate-gallery-medium.mjs)
 * used as the srcset candidate for the lightbox carousel on smaller screens.
 */
export function mediumSrc(src) {
  return src.replace(/\.webp$/, '-900.webp')
}
